name: build

on: [push]

env:
 RELEASE_KEYWORD: '[release]'
 SOLUTION_FILE: './source/Celerik.NetCore.Util.sln'
 TEST_PROJECT: './source/Celerik.NetCore.Util.Test/Celerik.NetCore.Util.Test.csproj'
 TEST_FOLDER: './source/Celerik.NetCore.Util.Test/'
 COVERAGE_FILE: './source/Celerik.NetCore.Util.Test/TestResults/coverage.info'

jobs:
  build:
    if: false == contains(github.event.head_commit.message, '[release]')
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2
    - name: Setup .net core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 3.1.100
    - name: Build with dotnet
      run: dotnet build ${{env.SOLUTION_FILE}} --configuration Release
    - name: Run unit tests
      run: dotnet test ${{env.TEST_PROJECT}}
    - name: Generate coverage report
      run: |
        cd ./source/Celerik.NetCore.Util.Test/
        dotnet test /p:CollectCoverage=true /p:CoverletOutput=TestResults/ /p:CoverletOutputFormat=lcov
    - name: Publish coverage report to coveralls.io
      uses: coverallsapp/github-action@master
      with:
        github-token: ${{ secrets.GITHUB_TOKEN }}
        path-to-lcov: ${{env.COVERAGE_FILE}}
