name: documentation

on:
  push:
    branches:
      - master

jobs:
  documentation:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v2
    - name: Build Documentation
      uses: nikeee/docfx-action@master
      with:
        args: source/DocFx/docfx.json
    - name: Publish documentation on github pages
      uses: maxheld83/ghpages@master
      env:
        BUILD_DIR: source/DocFx/_site
        GH_PAT: ${{ secrets.DEPLOY_DOCUMENTATION_PERSONAL_ACCESS_TOKEN }}
