name: documentation

on:
  push:
    branches:
      - master

jobs:
  documentation:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v2
 
    - uses: nikeee/docfx-action@master
      name: Build Documentation
      with:
        args: source/Documentation/docfx.json

    - uses: maxheld83/ghpages@master
      name: Publish Documentation on GitHub Pages
      env:
        BUILD_DIR: source/Documentation/_site
        GH_PAT: ${{ secrets.GH_PAT }}
