name: Nuget Package Deploy

on:
  push:
    branches:
      - master

jobs:
  build:
    if: contains('[release]', toJson(github.event.pull_request))
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 3.1.100

    - name: Build with dotnet
      run: dotnet build ./source/Celerik.NetCore.sln --configuration Release

    - name: Run unit tests
      run: dotnet test ./source/Celerik.NetCore.Util.Test/Celerik.NetCore.Util.Test.csproj

  deploy:
    needs: build
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v2
    
    - name: Pack nuget Package
      run: dotnet pack ./source/Celerik.NetCore.sln --configuration Release

    - name: Push nuget Package
      run: dotnet nuget push **/*.nupkg
           --api-key ${{ secrets.CELERIK_NUGET_API_KEY }}
           --source https://api.nuget.org/v3/index.json
